name: Tests

on: 
  - push
  - pull_request

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: snakemake
      uses: snakemake/snakemake-github-action@v1.2.0
      with:
        directory: ./
        snakefile: ./Snakefile
        args: "--use-conda"
