name: snakemake-base

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.4.0
        with:
          directory: ./
          args: "--use-conda"
