name: snakemake-base

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: snakemake/snakemake-github-action@v1.4.0
    - uses: ./
      with:
        directory: ./
        snakefile: ./Snakefile
        args: --use-conda
